project:
  type: website
  output-dir: docs

website:
  title: "Kevin Li"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: kevin.qmd
        text: About me
      - text: Research
        menu: 
          - text: Themes
            href: research.qmd
          - text: Projects
            href: projects.qmd
      - href: publications.qmd
        text: Publications
      - posts.qmd

format:
  html:
    theme: 
      - journal
      - custom.scss
    css: styles.css
    toc: true

editor: visual

