project:
  type: website
  output-dir: docs

website:
  title: "Kevin Li"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: kevin.qmd
        text: About me
      - text: Work
        menu:
          - text: Research
            href: research.qmd
          - text: Data
            href: data.qmd
          - text: Design
            href: design.qmd
      - href: publications.qmd
        text: Publications
      - posts.qmd
  page-footer: 
    left: "Copyright 2026, Kevin Li" 
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/neivk/
      - icon: file-earmark-text
        href: https://scholar.google.com/citations?user=JQkwWL4AAAAJ
      - icon: beaker
        href: https://www.researchgate.net/profile/Kevin-Li-39
      - icon: github
        href: https://github.com/KwnLi
  favicon: media/favicon2.ico
format:
  html:
    theme: 
      - journal
      - custom.scss
    css: styles.css
    toc: true

editor: visual

