---
title: "Ecological Landscape Planning"
format: html
listing:
  - id: projects-es
    contents: "projects/*/*.qmd"
    include:
      category: "ecosystem services"
    type: grid
    grid-columns: 1
    sort-ui: false
    sort: "date desc"
    fields: [image, title, description]
---

I am interested in ecological landscape design -- integrating ecological understanding into how we plan space, from the scale of vacant lots to watersheds. In addition to being an ecologist, I have a Master's in Landscape Architecture from the University of Michigan. I also consult on ecologically-based landscape planning and design in spaces like farms, urban gardens, and pocket forests.

## Designing for ecosystem services in the landscape

_How can we design landscapes that leverage ecological processes for multiple ecosystem services?_ My research investigates how the landscape influences ecosystem functions and services like pollination, water purification, and crop production through the composition and configuration of natural habitats and human land uses.

### Relevant Work

::::{#projects-es}
::::