---
title: "Research Projects"
format: html
---

### Landscape Floral Resource Continuity and Connectivity

Insect pollinators rely on floral resources in their landscape, while their visits to flowering plants can provide pollination. My ongoing work seeks to better understand what floral resources are available to pollinators over space and time. I am developing projects that use citizen science data and satellite imagery to map floral communities.

### BeeSpatial

I develop the web application BeeSpatial as a research-focused complement to Beescape, an interactive map-based application that helps users assess landscape quality for supporting bees and other pollinators. BeeSpatial helps researchers access a trove of habitat and environmental landscape data, including predicted seasonal floral resources, bee nesting habitat, land cover, and climate variables.

### Modeling Landscape Agroecosystem Services

My recently published work shows that distinct aspects of landscape composition and configuration maximize different ecosystem services through nonlinear relationships, suggesting thresholds or tipping points (Li and Goslee 2025, Landscape Ecol).

## Completed Research Projects

### Coffee Leaf Rust Transmission Dynamics and Tipping Points

I applied a tipping point indicator from engineering to understand the spatiotemporal dynamics of annual resurgences of the coffee leaf rust (Hemileia vastatrix) in a Mexican farm (Li et al. 2022, Sci Rep).

### Pollinators in Oil Palm Landscapes

In my dissertation work in Indonesia, I found that oil palm pollinators may benefit from mesopredator-suppressing effects, e.g. insectivorous birds that spill over from the forest into the oil palm farm (Li et al. 2023, Agric Ecosyst Environ).
