---
title: "My Research"
format: html
---

## Research Themes

My research investigates how ecology and society interact in a landscape context. I conduct field and computational research in ecology to look for solutions that integrate human activity within the larger landscape system. My goal is to find sustainable and equitable ways to fulfill people’s needs while restoring and protecting natural ecosystems.

### Understanding spatial patterns of ecological processes

A recurring theme of my work is inferring pattern from the spatial organization of ecological phenomena. I want to understand, to what degree do ecological processes organize and influence their own spatial distribution (are **endogenous**), as opposed to reflect their environmental (**exogenous**) context?

### Optimizing landscape ecosystem services

Can we design landscapes leverage ecological processes to optimize multiple ecosystem services, like pollination and crop production? This requires understanding how the landscape influences ecosystem functions and services through the composition and configuration of various types of natural habitats versus human land uses.

### Supporting data-driven decision making in conservation and environment

Ecological data is messy and complex. I am use a variety of applied statistical methods, from spatially explicit point process models to generalized linear mixed effects models to disentangle ecological patterns. I am also interested in developing tools that make landscape data and dynamic processes accessible to a wide audience.

### Understanding factors of landscape transformation

A landscape is a complex system where social, historical, and ecological forces interact. My work searches for leverage points where relatively small changes can lead to broader impacts, to apply in building resilient socio-ecological systems.

## Research Projects

### Landscape Floral Resource Continuity and Connectivity

Insect pollinators rely on floral resources in their landscape, while their visits to flowering plants can provide pollination. My ongoing work seeks to better understand what floral resources are available to pollinators over space and time. I am developing projects that use citizen science data and satellite imagery to map floral communities.

### BeeSpatial

I develop the web application [BeeSpatial](https://beesuite.psu.edu/beespatial/) as a research-focused complement to [Beescape](https://beescape.psu.edu/), an interactive map-based application that helps users assess landscape quality for supporting bees and other pollinators. BeeSpatial helps researchers access a trove of habitat and environmental landscape data, including predicted seasonal floral resources, bee nesting habitat, land cover, and climate variables.

### Modeling Landscape Agroecosystem Services

My recently published work shows that distinct aspects of landscape composition and configuration maximize different ecosystem services through nonlinear relationships, suggesting thresholds or tipping points (Li and Goslee 2025, *Landscape Ecol*).

## Completed Research Projects

### Coffee Leaf Rust Transmission Dynamics and Tipping Points

I applied a tipping point indicator from engineering to understand the spatiotemporal dynamics of annual resurgences of the coffee leaf rust (*Hemileia vastatrix*) in a Mexican farm (Li *et al.* 2022, *Sci Rep*).

### Pollinators in Oil Palm Landscapes

In my dissertation work in Indonesia, I found that oil palm pollinators may benefit from mesopredator-suppressing effects, e.g. insectivorous birds that spill over from the forest into the oil palm farm (Li et al. 2023, *Agric Ecosyst Environ*).
